# Generated by Django 3.2.3 on 2021-07-07 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
        ('carrito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cuentas.perfil'),
        ),
    ]
