# Generated by Django 3.2.3 on 2021-07-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0002_total_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='total',
            name='cantidad',
            field=models.SmallIntegerField(null=True, verbose_name='Cantidad'),
        ),
    ]
