# Generated by Django 3.2.3 on 2021-07-01 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('busqueda_juego', models.CharField(
                    max_length=50, verbose_name='Nombre del juego')),
            ],
        ),
    ]
