# Generated by Django 3.2.3 on 2021-07-01 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_juego'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Juego',
        ),
    ]
