# Generated by Django 3.2.3 on 2021-07-07 00:57

import apps.producto.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_auto_20210706_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=apps.producto.models.cambiar_nombre, verbose_name='Imagen'),
        ),
    ]
